### ISSUE TITLE
How to use this with GridLayout ?

### ISSUE THREAD

**Issue by nerviantone** [Fueled/reclaim#19]
I am a beginer programmer and I was wondering if this could be implemented using grid layout instead of linear layout.

**Comment by husseinala** [comment]
Hi @nerviantone, yeah this could be used with any `RecyclerView` layout. All you have to do is specify the layout type you want to use and pass it to the recycler view. e.g.

``` kotlin
val manager = GridLayoutManager(...)
recyclerView.setLayoutManager(manager)
```
